<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CommonLib</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>

</Project>
